---

- name: Create firewalld configuration file for GlusterFS
  copy:
    src: etc/firewalld/services/glusterfs.xml
    dest: /etc/firewalld/services/glusterfs.xml
    owner: root
    group: root
    mode: 0644
  register: firewallgluster

# Si ajout/modification FW gluster (modif firewallgluster), reload firewalld 
# en attendant de pouvoir déclencher un handler imméadiatement
# cf. https://github.com/ansible/ansible/issues/10829
- name: Reload firewalld
  service:
    name: firewalld
    enabled: yes
    state: reloaded
  when: firewallgluster.changed

- name: Configure firewalld
  firewalld:
    zone: public
    service: glusterfs
    state: enabled
    permanent: True
    immediate: True
